### ISSUE TITLE
syntax error class Camera(metaclass=ABCMeta):

### ISSUE THREAD

**Issue by anaismoller** [Samreay/SurveyVisualiser#4]
when trying the example:
python examples.py 

Traceback (most recent call last):
  File "examples.py", line 1, in <module>
    from surveyvis.camera import OrbitZoomCamera

SurveyVisualiser-master/surveyvis/camera.py", line 5
    class Camera(metaclass=ABCMeta):
                          ^
SyntaxError: invalid syntax

**Comment by Samreay** [comment]
Can I confirm that you've added the root directory to the path and are trying to run it using python3?

**Comment by anaismoller** [comment]
error using python 2.7, will try with 3 then.

**Comment by Samreay** [comment]
Hey Anais, did it end up working with py3?
